services:
  gmail-login:
    build: .
    volumes:
      - /var/www/login-google:/app/screenshots
    environment:
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
    working_dir: /app
    stdin_open: true
    tty: true
